-- 创建自定义 AI 模型表
CREATE TABLE IF NOT EXISTS custom_ai_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,           
    provider VARCHAR(100) NOT NULL,        
    api_base_url TEXT NOT NULL,            
    api_key TEXT NOT NULL,                
    model_name VARCHAR(255) NOT NULL,      
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 创建用户 AI 配置表
CREATE TABLE IF NOT EXISTS user_ai_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    current_model_id BIGINT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_ai_profiles_user_id_current_model_id
ON user_ai_profiles(user_id, current_model_id);